version: "3.8"

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: referral_system
    volumes:
      - .:/referral_system
    ports:
      - "8000:8000"
